### ISSUE TITLE
Not work 

### ISSUE THREAD

**Issue by RobinCK** [ashvin777/FamilyTree#1]
@ashvin777 not work 
https://monosnap.com/file/QjPquzbnacklhpbfdDcvCIv4fCyjLs 
https://monosnap.com/file/X3FrgtTLWv5YlaEL3NAakneTLjUtFK

**Comment by ashvin777** [comment]
Hi Robin,

Thanks for reporting this. actually this is under development and I am yet to publish the stable clapp. I will let you know once it will be available for beta testing 😊.

**Comment by RobinCK** [comment]
Thanks, I will wait

**Comment by RobinCK** [comment]
Hi @ashvin777 your example not working https://monosnap.com/file/4Mz62OkRRGRX54NldheAfnQSgROwTn

**Comment by ashvin777** [comment]
Hi Robin,

Request you clean the cache and try again. It seems the cache of last time(during development) is still there which may be causing this error.

Regards,
Ashvin

**Comment by ashvin777** [comment]
Is it working now ?
